### ISSUE TITLE
search function

### ISSUE THREAD

**Issue by rcolpo** [javix64/web_scraping_vinted2.0#1]
Is it possible to show only the results of a particular brand, or size?
In this case, how to modify main_url='https://www.vinted.es/api/v2/items?per_page=96&page='

Thank you.

**Comment by javix64** [comment]
in this moment i don't know how you can do it.
But, you can scrap it, and after in CSV you can filter the data by brand, or size.

**Comment by javix64** [comment]
the url for scrap Brands is: https://www.vinted.es/api/v2/items?brand_ids=53 -> this is Nike brand.
the only thing, you must change the main_url for this.
In the same way if you want size, you can filter with this: size_ids=X. where X is the size id that they have.

**Comment by rcolpo** [comment]
Thank you very much! So far, I was using selenium to navigate in Vinted and retrieve data, but your approach seems much more efficient. Thank you very much <3

**Comment by javix64** [comment]
I feel so good that this script helps you. don't forget star the project! 
Thanks a lot! Maybe in the future i will add search option! :D
